disabled_rules:
    - closing_brace
    - colon
    - comma
#   - conditional_binding_cascade
#   - control_statement
    - cyclomatic_complexity
#   - empty_count
    - file_length
    - force_cast
#   - force_try
    - force_unwrapping
    - function_body_length
#   - leading_whitespace
    - legacy_constant
#   - legacy_constructor
#   - line_length
#   - missing_docs
    - nesting
#   - opening_brace
#   - operator_whitespace
#   - return_arrow_whitespace
#   - statement_position
    - shorthand_operator
    - todo
#   - trailing_newline
#   - trailing_semicolon
    - trailing_whitespace
    - type_body_length
    - type_name
    - variable_name
    - valid_docs

included:
    - harp 

excluded:
    - Pods

line_length:
  warning: 130
  error:   300

type_body_length:
  warning: 1000
  error:   2000

function_parameter_count:
  warning: 8
  error:   8

variable_name:
  max_length:
    warning: 40
    error:   40
